#!/bin/bash
# Generate nginx reverse proxy config for ntfy
# Usage: bash setup-nginx.sh --domain ntfy.yourdomain.com
set -e

DOMAIN=""
PORT=8080
SSL=true

while [[ $# -gt 0 ]]; do
    case $1 in
        --domain) DOMAIN="$2"; shift 2 ;;
        --port) PORT="$2"; shift 2 ;;
        --no-ssl) SSL=false; shift ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

if [ -z "$DOMAIN" ]; then
    echo "Usage: setup-nginx.sh --domain ntfy.yourdomain.com [--port 8080] [--no-ssl]"
    exit 1
fi

CONF_PATH="/etc/nginx/sites-available/ntfy.conf"

if [ "$SSL" = true ]; then
    cat <<EOF | sudo tee "$CONF_PATH"
# ntfy reverse proxy with SSL
# Generated by ntfy-server skill

upstream ntfy_backend {
    server 127.0.0.1:${PORT};
}

server {
    listen 80;
    server_name ${DOMAIN};
    
    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://ntfy_backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket support (for subscribe)
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        # Long polling support
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;

        # Buffering off for streaming
        proxy_buffering off;
    }
}
EOF
else
    cat <<EOF | sudo tee "$CONF_PATH"
# ntfy reverse proxy (no SSL)
server {
    listen 80;
    server_name ${DOMAIN};

    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400s;
        proxy_buffering off;
    }
}
EOF
fi

echo "✅ Nginx config written to $CONF_PATH"
echo ""
echo "Next steps:"
echo "  sudo ln -sf $CONF_PATH /etc/nginx/sites-enabled/ntfy.conf"
echo "  sudo nginx -t && sudo systemctl reload nginx"
if [ "$SSL" = true ]; then
    echo ""
    echo "  # Get SSL cert first (if not already):"
    echo "  sudo certbot certonly --nginx -d ${DOMAIN}"
fi

# Update ntfy config to enable behind-proxy
if [ -f /etc/ntfy/server.yml ]; then
    if grep -q "behind-proxy:" /etc/ntfy/server.yml; then
        sudo sed -i 's/behind-proxy:.*/behind-proxy: true/' /etc/ntfy/server.yml
    else
        echo "behind-proxy: true" | sudo tee -a /etc/ntfy/server.yml
    fi
    echo ""
    echo "  # Updated /etc/ntfy/server.yml: behind-proxy: true"
    echo "  sudo systemctl restart ntfy"
fi
