#!/bin/bash
# Configure Unbound DNS resolver
set -euo pipefail

# Defaults
MODE="recursive"
LISTEN="${UNBOUND_LISTEN:-127.0.0.1}"
PORT="${UNBOUND_PORT:-53}"
CACHE_SIZE="${UNBOUND_CACHE_SIZE:-256m}"
NUM_THREADS="${UNBOUND_NUM_THREADS:-$(nproc 2>/dev/null || echo 2)}"
VERBOSITY="${UNBOUND_VERBOSITY:-1}"
UPSTREAM_SERVERS=()
DOT=false
ACCESS_CONTROL=""

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --mode) MODE="$2"; shift 2 ;;
        --listen) LISTEN="$2"; shift 2 ;;
        --port) PORT="$2"; shift 2 ;;
        --upstream) shift; while [[ $# -gt 0 && ! "$1" =~ ^-- ]]; do UPSTREAM_SERVERS+=("$1"); shift; done ;;
        --dot) DOT=true; shift ;;
        --access-control) ACCESS_CONTROL="$2"; shift 2 ;;
        --cache-size) CACHE_SIZE="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# Determine config path
CONF_DIR="/etc/unbound"
if command -v brew &>/dev/null && [ -d "$(brew --prefix)/etc/unbound" ]; then
    CONF_DIR="$(brew --prefix)/etc/unbound"
fi
CONF_FILE="$CONF_DIR/unbound.conf"

echo "=== Unbound Configuration ==="
echo "Mode: $MODE | Listen: $LISTEN:$PORT | Threads: $NUM_THREADS | Cache: $CACHE_SIZE"

# Backup existing config
if [ -f "$CONF_FILE" ]; then
    sudo cp "$CONF_FILE" "$CONF_FILE.backup.$(date +%s)"
    echo "[i] Backed up existing config"
fi

# Build config
build_config() {
    cat <<EOF
# Unbound configuration — generated by unbound-dns skill
# $(date -u +%Y-%m-%dT%H:%M:%SZ)

server:
    verbosity: $VERBOSITY
    interface: $LISTEN
    port: $PORT
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    # Performance tuning
    num-threads: $NUM_THREADS
    msg-cache-slabs: $NUM_THREADS
    rrset-cache-slabs: $NUM_THREADS
    infra-cache-slabs: $NUM_THREADS
    key-cache-slabs: $NUM_THREADS
    msg-cache-size: $(echo "$CACHE_SIZE" | sed 's/m$//')m
    rrset-cache-size: $CACHE_SIZE
    cache-min-ttl: 300
    cache-max-ttl: 86400
    prefetch: yes
    prefetch-key: yes
    serve-expired: yes
    serve-expired-ttl: 86400

    # Security hardening
    hide-identity: yes
    hide-version: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-below-nxdomain: yes
    harden-referral-path: yes
    use-caps-for-id: yes
    unwanted-reply-threshold: 10000
    val-clean-additional: yes

    # Privacy
    qname-minimisation: yes
    aggressive-nsec: yes
    minimal-responses: yes

    # Root hints
    root-hints: "$CONF_DIR/root.hints"

    # Trust anchor for DNSSEC
    auto-trust-anchor-file: "$CONF_DIR/root.key"

    # Access control
    access-control: 127.0.0.0/8 allow
    access-control: ::1/128 allow
EOF

    # Additional access control
    if [ -n "$ACCESS_CONTROL" ]; then
        echo "    access-control: $ACCESS_CONTROL"
    fi

    # Blocklist include (if exists)
    if [ -f "$CONF_DIR/blocklist.conf" ]; then
        echo ""
        echo "    # Ad-blocking"
        echo "    include: \"$CONF_DIR/blocklist.conf\""
    fi

    # Local zones include (if exists)
    if [ -f "$CONF_DIR/local-zones.conf" ]; then
        echo ""
        echo "    # Custom local zones"
        echo "    include: \"$CONF_DIR/local-zones.conf\""
    fi

    # Forward zone (if forward mode)
    if [ "$MODE" = "forward" ]; then
        echo ""
        echo "forward-zone:"
        echo "    name: \".\""
        if [ "$DOT" = true ]; then
            echo "    forward-tls-upstream: yes"
        fi
        for server in "${UPSTREAM_SERVERS[@]:-1.1.1.1 9.9.9.9}"; do
            if [ "$DOT" = true ]; then
                # Extract IP and port
                local ip="${server%%@*}"
                echo "    forward-addr: ${ip}@853"
            else
                echo "    forward-addr: $server"
            fi
        done
    fi

    # Remote control
    echo ""
    echo "remote-control:"
    echo "    control-enable: yes"
    echo "    control-interface: 127.0.0.1"
    echo "    control-port: 8953"
    echo "    server-key-file: \"$CONF_DIR/unbound_server.key\""
    echo "    server-cert-file: \"$CONF_DIR/unbound_server.pem\""
    echo "    control-key-file: \"$CONF_DIR/unbound_control.key\""
    echo "    control-cert-file: \"$CONF_DIR/unbound_control.pem\""
}

# Write config
echo "[*] Writing config to $CONF_FILE..."
build_config | sudo tee "$CONF_FILE" > /dev/null

# Fetch root trust anchor for DNSSEC
if command -v unbound-anchor &>/dev/null; then
    echo "[*] Fetching DNSSEC root trust anchor..."
    sudo unbound-anchor -a "$CONF_DIR/root.key" 2>/dev/null || true
    echo "[✓] DNSSEC trust anchor updated"
fi

# Validate config
echo "[*] Validating configuration..."
if sudo unbound-checkconf "$CONF_FILE"; then
    echo "[✓] Configuration valid"
else
    echo "❌ Configuration invalid. Check $CONF_FILE"
    exit 1
fi

# Start/restart service
echo "[*] Starting Unbound..."
if command -v systemctl &>/dev/null; then
    sudo systemctl enable unbound
    sudo systemctl restart unbound
    sleep 1
    if systemctl is-active --quiet unbound; then
        echo "[✓] Unbound is running"
    else
        echo "❌ Unbound failed to start. Check: sudo journalctl -u unbound -n 20"
        exit 1
    fi
elif command -v brew &>/dev/null; then
    brew services restart unbound
    echo "[✓] Unbound restarted via Homebrew"
else
    sudo unbound -c "$CONF_FILE" -d &
    echo "[✓] Unbound started in background"
fi

# Update resolv.conf to use local resolver
if [ "$LISTEN" = "127.0.0.1" ] || [ "$LISTEN" = "0.0.0.0" ]; then
    echo "[*] Updating /etc/resolv.conf to use local resolver..."
    if [ ! -L /etc/resolv.conf ] || [ "$(readlink /etc/resolv.conf)" != "../run/systemd/resolve/stub-resolv.conf" ]; then
        echo "nameserver 127.0.0.1" | sudo tee /etc/resolv.conf > /dev/null
        echo "[✓] System DNS set to 127.0.0.1"
    else
        echo "[i] resolv.conf is managed by systemd — update manually or disable systemd-resolved"
    fi
fi

echo ""
echo "=== Configuration Complete ==="
echo "Run 'bash scripts/verify.sh' to test your resolver."
