#!/bin/bash
# Configure Unbound DNS resolver
set -euo pipefail

MODE="recursive"
UPSTREAM="quad9"
CUSTOM_DNS=""
DNSSEC="on"
LOGGING=""
ALLOW_NETWORK=""
INTERFACE="127.0.0.1"
THREADS=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 2)

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --mode) MODE="$2"; shift 2 ;;
        --upstream) UPSTREAM="$2"; shift 2 ;;
        --dns) CUSTOM_DNS="$2"; shift 2 ;;
        --dnssec) DNSSEC="$2"; shift 2 ;;
        --logging) LOGGING="$2"; shift 2 ;;
        --allow-network) ALLOW_NETWORK="$2"; shift 2 ;;
        --interface) INTERFACE="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# Detect config path
CONF_DIR="/etc/unbound"
if [[ "$(uname)" == "Darwin" ]]; then
    CONF_DIR="$(brew --prefix)/etc/unbound"
fi
CONF_FILE="$CONF_DIR/unbound.conf"

echo "⚙️  Configuring Unbound (mode: $MODE)..."

# Backup existing config
if [[ -f "$CONF_FILE" ]]; then
    cp "$CONF_FILE" "$CONF_FILE.bak.$(date +%s)"
    echo "📋 Backed up existing config"
fi

# Build forward zone config
build_forward_zone() {
    local dns_servers=""
    case "$UPSTREAM" in
        cloudflare)
            dns_servers='    forward-addr: 1.1.1.1@853
    forward-addr: 1.0.0.1@853'
            ;;
        quad9)
            dns_servers='    forward-addr: 9.9.9.9@853
    forward-addr: 149.112.112.112@853'
            ;;
        google)
            dns_servers='    forward-addr: 8.8.8.8@853
    forward-addr: 8.8.4.4@853'
            ;;
        custom)
            for dns in $CUSTOM_DNS; do
                dns_servers+="    forward-addr: $dns"$'\n'
            done
            ;;
    esac
    cat <<EOF
forward-zone:
    name: "."
    forward-tls-upstream: yes
$dns_servers
EOF
}

# Build access control
build_access_control() {
    echo "    access-control: 127.0.0.0/8 allow"
    echo "    access-control: ::1/128 allow"
    if [[ -n "$ALLOW_NETWORK" ]]; then
        echo "    access-control: $ALLOW_NETWORK allow"
    fi
    echo "    access-control: 0.0.0.0/0 refuse"
    echo "    access-control: ::/0 refuse"
}

# Build logging config
build_logging() {
    if [[ "$LOGGING" == "on" ]]; then
        cat <<EOF
    log-queries: yes
    log-replies: yes
    log-local-actions: yes
    verbosity: 1
    logfile: "/var/log/unbound/unbound.log"
EOF
    else
        cat <<EOF
    log-queries: no
    log-replies: no
    verbosity: 0
EOF
    fi
}

# Build blocklist include
build_blocklist() {
    if [[ "$MODE" == "adblock" ]]; then
        local blocklist="$CONF_DIR/blocklist.conf"
        if [[ ! -f "$blocklist" ]]; then
            echo "📥 Downloading initial blocklist..."
            bash "$(dirname "$0")/update-blocklist.sh"
        fi
        echo "    include: \"$blocklist\""
    fi
}

# DNSSEC config
build_dnssec() {
    if [[ "$DNSSEC" == "on" ]]; then
        cat <<EOF
    auto-trust-anchor-file: "/etc/unbound/root.key"
    val-clean-additional: yes
    harden-dnssec-stripped: yes
EOF
    fi
}

# Write main config
cat > "$CONF_FILE" <<EOF
# Unbound configuration — generated by unbound-dns skill
# Mode: $MODE | Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)

server:
    interface: $INTERFACE
    port: 53
    do-ip4: yes
    do-ip6: yes
    do-udp: yes
    do-tcp: yes

    # Performance
    num-threads: $THREADS
    msg-cache-slabs: $THREADS
    rrset-cache-slabs: $THREADS
    infra-cache-slabs: $THREADS
    key-cache-slabs: $THREADS
    msg-cache-size: 64m
    rrset-cache-size: 128m
    cache-min-ttl: 300
    cache-max-ttl: 86400
    prefetch: yes
    prefetch-key: yes
    serve-expired: yes
    serve-expired-ttl: 3600

    # Privacy
    hide-identity: yes
    hide-version: yes
    qname-minimisation: yes
    aggressive-nsec: yes

    # Security
    harden-glue: yes
    harden-below-nxdomain: yes
    harden-referral-path: yes
    use-caps-for-id: yes
    harden-algo-downgrade: yes
    harden-large-queries: yes
    unwanted-reply-threshold: 10000

    # DNSSEC
$(build_dnssec)

    # Root hints
    root-hints: "$CONF_DIR/root.hints"

    # Access control
$(build_access_control)

    # Logging
$(build_logging)

    # Blocklist
$(build_blocklist)

    # Hardening
    private-address: 10.0.0.0/8
    private-address: 172.16.0.0/12
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: fd00::/8
    private-address: fe80::/10

EOF

# Add forward zone for forwarding mode
if [[ "$MODE" == "forwarding" ]]; then
    build_forward_zone >> "$CONF_FILE"
fi

# Validate config
echo "🔍 Validating configuration..."
if unbound-checkconf "$CONF_FILE" 2>/dev/null; then
    echo "✅ Configuration valid"
else
    echo "⚠️  Config validation failed — check $CONF_FILE"
    exit 1
fi

# Create log directory
if [[ "$LOGGING" == "on" ]]; then
    sudo mkdir -p /var/log/unbound
    sudo chown unbound:unbound /var/log/unbound 2>/dev/null || true
fi

# Restart Unbound
echo "🔄 Restarting Unbound..."
if command -v systemctl &>/dev/null; then
    sudo systemctl enable unbound 2>/dev/null || true
    sudo systemctl restart unbound
elif command -v brew &>/dev/null; then
    brew services restart unbound
elif command -v rc-service &>/dev/null; then
    sudo rc-service unbound restart
fi

echo ""
echo "✅ Unbound configured in $MODE mode"
echo "   Config: $CONF_FILE"
echo "   Listening: $INTERFACE:53"
echo "   DNSSEC: $DNSSEC"
[[ "$MODE" == "forwarding" ]] && echo "   Upstream: $UPSTREAM (TLS)"
[[ "$MODE" == "adblock" ]] && echo "   Ad-blocking: enabled"
echo ""
echo "Test: dig @127.0.0.1 example.com"
