#!/bin/bash
# SearXNG Installation Script
# Supports Docker and bare-metal installation

set -euo pipefail

# Defaults
METHOD="docker"
PORT=8080
BASE_URL=""
CONFIG_DIR="${SEARXNG_CONFIG_DIR:-$HOME/.config/searxng}"
CONTAINER_NAME="searxng"
IMAGE="searxng/searxng:latest"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${GREEN}✅${NC} $1"; }
warn() { echo -e "${YELLOW}⚠️${NC} $1"; }
err() { echo -e "${RED}❌${NC} $1" >&2; }

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Options:
  --method <docker|bare-metal>  Installation method (default: docker)
  --port <port>                 Port to run on (default: 8080)
  --base-url <url>              Base URL for reverse proxy
  --config-dir <path>           Config directory (default: ~/.config/searxng)
  --container-name <name>       Docker container name (default: searxng)
  -h, --help                    Show this help

Examples:
  $(basename "$0") --method docker --port 8080
  $(basename "$0") --method docker --port 8080 --base-url https://search.example.com
EOF
  exit 0
}

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --method) METHOD="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --base-url) BASE_URL="$2"; shift 2 ;;
    --config-dir) CONFIG_DIR="$2"; shift 2 ;;
    --container-name) CONTAINER_NAME="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) err "Unknown option: $1"; exit 1 ;;
  esac
done

# Generate secret key
generate_secret() {
  openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '/+=' | head -c 64
}

# Create default settings.yml
create_config() {
  local secret_key
  secret_key=$(generate_secret)
  
  mkdir -p "$CONFIG_DIR"
  mkdir -p "$CONFIG_DIR/backups"
  
  if [[ -f "$CONFIG_DIR/settings.yml" ]]; then
    warn "Config already exists at $CONFIG_DIR/settings.yml — keeping existing"
    return
  fi
  
  local base_url_line="base_url: false"
  if [[ -n "$BASE_URL" ]]; then
    base_url_line="base_url: \"$BASE_URL\""
  fi
  
  cat > "$CONFIG_DIR/settings.yml" <<YAML
# SearXNG Configuration
# Generated by searxng-manager on $(date -u +%Y-%m-%dT%H:%M:%SZ)

use_default_settings: true

general:
  instance_name: "SearXNG"
  debug: false
  enable_metrics: true

search:
  safe_search: 0
  default_lang: "en"
  autocomplete: "google"
  formats:
    - html
    - json

server:
  port: ${PORT}
  bind_address: "0.0.0.0"
  secret_key: "${secret_key}"
  ${base_url_line}
  limiter: true
  image_proxy: true

ui:
  default_theme: simple
  results_on_new_tab: false
  infinite_scroll: true
  static_use_hash: true

outgoing:
  request_timeout: 6.0
  max_request_timeout: 15.0
  pool_maxsize: 20
  pool_connections: 100

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: bing
    engine: bing
    shortcut: b
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false

  - name: arxiv
    engine: arxiv
    shortcut: arx
    disabled: false

  - name: stackoverflow
    engine: stackoverflow
    shortcut: so
    disabled: false
YAML

  log "Config created at $CONFIG_DIR/settings.yml"
}

# Docker installation
install_docker() {
  echo "🔍 Checking Docker..."
  
  if ! command -v docker &>/dev/null; then
    err "Docker not found. Install Docker first:"
    echo "  curl -fsSL https://get.docker.com | sh"
    echo "  sudo usermod -aG docker \$USER"
    exit 1
  fi
  
  log "Docker found: $(docker --version)"
  
  # Check if container already running
  if docker ps -q -f name="$CONTAINER_NAME" 2>/dev/null | grep -q .; then
    warn "Container '$CONTAINER_NAME' is already running"
    echo "  Stop it first: docker stop $CONTAINER_NAME && docker rm $CONTAINER_NAME"
    exit 1
  fi
  
  # Remove stopped container if exists
  docker rm "$CONTAINER_NAME" 2>/dev/null || true
  
  # Create config
  create_config
  
  # Pull image
  echo "📥 Pulling SearXNG image..."
  docker pull "$IMAGE"
  
  # Run container
  echo "🚀 Starting SearXNG..."
  docker run -d \
    --name "$CONTAINER_NAME" \
    --restart unless-stopped \
    -p "${PORT}:8080" \
    -v "${CONFIG_DIR}:/etc/searxng" \
    -e "SEARXNG_BASE_URL=${BASE_URL:-http://localhost:${PORT}/}" \
    "$IMAGE"
  
  # Wait for startup
  echo "⏳ Waiting for SearXNG to start..."
  for i in $(seq 1 30); do
    if curl -s -o /dev/null -w "%{http_code}" "http://localhost:${PORT}/" 2>/dev/null | grep -q "200\|302"; then
      log "SearXNG is running at http://localhost:${PORT}"
      echo ""
      echo "📋 Quick reference:"
      echo "  Web UI:    http://localhost:${PORT}"
      echo "  API:       http://localhost:${PORT}/search?q=test&format=json"
      echo "  Config:    ${CONFIG_DIR}/settings.yml"
      echo "  Logs:      docker logs ${CONTAINER_NAME}"
      echo "  Stop:      docker stop ${CONTAINER_NAME}"
      echo "  Manage:    bash scripts/manage.sh status"
      return
    fi
    sleep 1
  done
  
  warn "SearXNG may still be starting. Check: docker logs ${CONTAINER_NAME}"
}

# Bare-metal installation
install_bare_metal() {
  echo "🔍 Checking prerequisites..."
  
  # Check Python
  if ! command -v python3 &>/dev/null; then
    err "Python 3.9+ required. Install: sudo apt install python3 python3-pip python3-venv"
    exit 1
  fi
  
  local py_version
  py_version=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
  log "Python $py_version found"
  
  local install_dir="${HOME}/searxng"
  
  if [[ -d "$install_dir" ]]; then
    warn "SearXNG directory exists at $install_dir"
    echo "  Remove it first: rm -rf $install_dir"
    exit 1
  fi
  
  # Clone SearXNG
  echo "📥 Cloning SearXNG..."
  git clone https://github.com/searxng/searxng.git "$install_dir"
  cd "$install_dir"
  
  # Create virtualenv
  echo "🐍 Setting up Python environment..."
  python3 -m venv venv
  source venv/bin/activate
  pip install -U pip setuptools wheel
  pip install -e .
  
  # Create config
  create_config
  cp "$CONFIG_DIR/settings.yml" "$install_dir/searx/settings.yml"
  
  # Create systemd service
  local service_file="/tmp/searxng.service"
  cat > "$service_file" <<SERVICE
[Unit]
Description=SearXNG Search Engine
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$install_dir
ExecStart=$install_dir/venv/bin/python -m searx.webapp
Environment=SEARXNG_SETTINGS_PATH=$install_dir/searx/settings.yml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SERVICE

  echo ""
  log "SearXNG installed at $install_dir"
  echo ""
  echo "📋 To run:"
  echo "  cd $install_dir && source venv/bin/activate && python -m searx.webapp"
  echo ""
  echo "📋 To install as systemd service:"
  echo "  sudo cp $service_file /etc/systemd/system/searxng.service"
  echo "  sudo systemctl daemon-reload"
  echo "  sudo systemctl enable --now searxng"
}

# Main
echo "🔎 SearXNG Manager — Installation"
echo "=================================="
echo "Method: $METHOD"
echo "Port:   $PORT"
echo "Config: $CONFIG_DIR"
echo ""

case $METHOD in
  docker) install_docker ;;
  bare-metal) install_bare_metal ;;
  *) err "Unknown method: $METHOD (use 'docker' or 'bare-metal')"; exit 1 ;;
esac
