#!/bin/bash
# Add a service route to Traefik via file provider (non-Docker services)
# For Docker services, just add labels to your container instead.

set -euo pipefail

TRAEFIK_DIR="/opt/traefik"
DOMAIN=""
TARGET=""
PORT=""
SERVICE_NAME=""
SSL=true

usage() {
  cat <<EOF
Usage: $0 --domain <domain> --target <host:port> [options]

Route external (non-Docker) services through Traefik.

Required:
  --domain <domain>     Domain to route (e.g., app.example.com)
  --target <host:port>  Backend server (e.g., 192.168.1.10:3000)

Options:
  --name <name>         Service name (default: derived from domain)
  --no-ssl              Don't enable SSL for this route
  --dir <path>          Traefik directory (default: /opt/traefik)
  -h, --help            Show this help

For Docker containers, use labels instead:
  docker run -l "traefik.enable=true" \
    -l "traefik.http.routers.myapp.rule=Host(\`app.example.com\`)" \
    -l "traefik.http.routers.myapp.tls.certresolver=letsencrypt" \
    -l "traefik.http.services.myapp.loadbalancer.server.port=3000" \
    --network traefik-public myapp:latest
EOF
  exit 0
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain) DOMAIN="$2"; shift 2 ;;
    --target) TARGET="$2"; shift 2 ;;
    --name) SERVICE_NAME="$2"; shift 2 ;;
    --no-ssl) SSL=false; shift ;;
    --dir) TRAEFIK_DIR="$2"; shift 2 ;;
    # Legacy compat
    --container) TARGET="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --ssl) SSL=true; shift ;;
    -h|--help) usage ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Handle legacy --container --port style
if [[ -n "$PORT" && -n "$TARGET" && ! "$TARGET" =~ : ]]; then
  TARGET="${TARGET}:${PORT}"
fi

if [[ -z "$DOMAIN" || -z "$TARGET" ]]; then
  echo "❌ --domain and --target are required"
  exit 1
fi

# Derive service name
if [[ -z "$SERVICE_NAME" ]]; then
  SERVICE_NAME=$(echo "$DOMAIN" | sed 's/[^a-zA-Z0-9]/-/g' | sed 's/^-//;s/-$//')
fi

# Ensure target has protocol
if [[ ! "$TARGET" =~ ^https?:// ]]; then
  TARGET="http://${TARGET}"
fi

CONFIG_FILE="${TRAEFIK_DIR}/config/${SERVICE_NAME}.yml"

TLS_BLOCK=""
if $SSL; then
  TLS_BLOCK="
      tls:
        certResolver: letsencrypt"
fi

cat > "$CONFIG_FILE" <<EOF
# Auto-generated by traefik-manager add-service
# Service: ${SERVICE_NAME}
# Domain: ${DOMAIN} → ${TARGET}
http:
  routers:
    ${SERVICE_NAME}:
      rule: "Host(\`${DOMAIN}\`)"
      service: ${SERVICE_NAME}
      entryPoints:
        - websecure${TLS_BLOCK}

  services:
    ${SERVICE_NAME}:
      loadBalancer:
        servers:
          - url: "${TARGET}"
EOF

echo "✅ Route added: ${DOMAIN} → ${TARGET}"
echo "   Config: ${CONFIG_FILE}"
echo "   Traefik will auto-detect this change (file provider watches directory)."
