#!/bin/bash
# JupyterLab Installer
# Installs Python3, pip, virtualenv, JupyterLab, and optional data science packages

set -euo pipefail

VENV_PATH="${JUPYTER_VENV:-$HOME/.jupyter-venv}"
WORKSPACE="${JUPYTER_HOME:-$HOME/jupyter-workspace}"
FULL_INSTALL=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --venv) VENV_PATH="$2"; shift 2 ;;
    --full) FULL_INSTALL=true; shift ;;
    --workspace) WORKSPACE="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: bash install.sh [--venv PATH] [--full] [--workspace PATH]"
      echo "  --venv PATH       Virtual environment path (default: ~/.jupyter-venv)"
      echo "  --full             Install data science packages (numpy, pandas, matplotlib, scipy, scikit-learn)"
      echo "  --workspace PATH   Notebook workspace directory (default: ~/jupyter-workspace)"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

echo "📦 JupyterLab Installer"
echo "========================"

# Detect OS and install Python if needed
install_python() {
  if command -v python3 &>/dev/null; then
    echo "✅ Python3 found: $(python3 --version)"
    return 0
  fi

  echo "📥 Installing Python3..."
  if command -v apt-get &>/dev/null; then
    sudo apt-get update -qq
    sudo apt-get install -y -qq python3 python3-pip python3-venv
  elif command -v dnf &>/dev/null; then
    sudo dnf install -y python3 python3-pip
  elif command -v yum &>/dev/null; then
    sudo yum install -y python3 python3-pip
  elif command -v pacman &>/dev/null; then
    sudo pacman -S --noconfirm python python-pip
  elif command -v brew &>/dev/null; then
    brew install python3
  else
    echo "❌ Could not detect package manager. Install Python3 manually."
    exit 1
  fi
  echo "✅ Python3 installed: $(python3 --version)"
}

# Create virtual environment
setup_venv() {
  if [ -d "$VENV_PATH" ]; then
    echo "✅ Virtual environment exists at $VENV_PATH"
  else
    echo "📦 Creating virtual environment at $VENV_PATH..."
    python3 -m venv "$VENV_PATH"
    echo "✅ Virtual environment created"
  fi
  # shellcheck disable=SC1091
  source "$VENV_PATH/bin/activate"
  pip install --quiet --upgrade pip
}

# Install JupyterLab
install_jupyter() {
  echo "📥 Installing JupyterLab..."
  pip install --quiet jupyterlab ipykernel

  if [ "$FULL_INSTALL" = true ]; then
    echo "📥 Installing data science packages..."
    pip install --quiet numpy pandas matplotlib scipy scikit-learn seaborn plotly ipywidgets
    echo "✅ Data science packages installed"
  fi

  echo "✅ JupyterLab installed: $(jupyter lab --version)"
}

# Setup workspace
setup_workspace() {
  mkdir -p "$WORKSPACE"
  echo "✅ Workspace directory: $WORKSPACE"
}

# Register Python kernel
register_kernel() {
  python3 -m ipykernel install --user --name python3 --display-name "Python 3" 2>/dev/null || true
  echo "✅ Python 3 kernel registered"
}

# Generate default config
generate_config() {
  local config_dir="$HOME/.jupyter"
  mkdir -p "$config_dir"

  if [ ! -f "$config_dir/jupyter_lab_config.py" ]; then
    cat > "$config_dir/jupyter_lab_config.py" << PYEOF
# JupyterLab Configuration
# Generated by jupyter-lab-manager

c.ServerApp.ip = '127.0.0.1'
c.ServerApp.port = 8888
c.ServerApp.open_browser = False
c.ServerApp.notebook_dir = '$WORKSPACE'
c.ServerApp.terminado_settings = {'shell_command': ['/bin/bash']}
PYEOF
    echo "✅ Config generated at $config_dir/jupyter_lab_config.py"
  else
    echo "✅ Config already exists at $config_dir/jupyter_lab_config.py"
  fi
}

# Save venv path for other scripts
save_env() {
  local env_file="$(dirname "$0")/../.env"
  cat > "$env_file" << EOF
JUPYTER_VENV="$VENV_PATH"
JUPYTER_HOME="$WORKSPACE"
JUPYTER_PORT="${JUPYTER_PORT:-8888}"
JUPYTER_IP="${JUPYTER_IP:-127.0.0.1}"
EOF
  echo "✅ Environment saved to .env"
}

# Main
install_python
setup_venv
install_jupyter
setup_workspace
register_kernel
generate_config
save_env

echo ""
echo "🎉 JupyterLab installed successfully!"
echo ""
echo "  Start:    bash scripts/run.sh start"
echo "  Workspace: $WORKSPACE"
echo "  Venv:     $VENV_PATH"
echo ""
