#!/bin/bash
# Borgmatic Backup Manager — Main entry point
set -euo pipefail

BORGMATIC_CONFIG="${BORGMATIC_CONFIG:-/etc/borgmatic/config.yaml}"
LOG_FILE="/var/log/borgmatic/borgmatic.log"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"; }

# ─── INIT ───────────────────────────────────────────────
cmd_init() {
  local repo="" encryption="repokey"
  while [[ $# -gt 0 ]]; do
    case $1 in
      --repo) repo="$2"; shift 2 ;;
      --encryption) encryption="$2"; shift 2 ;;
      *) echo "Unknown option: $1"; exit 1 ;;
    esac
  done
  [[ -z "$repo" ]] && { echo "❌ --repo is required"; exit 1; }

  log "🔧 Initializing Borg repository at $repo (encryption: $encryption)..."
  borg init --encryption="$encryption" "$repo"
  log "✅ Repository initialized: $repo"
}

# ─── CONFIGURE ──────────────────────────────────────────
cmd_configure() {
  local repo="" sources="" passfile="" keep_daily=7 keep_weekly=4 keep_monthly=6 keep_yearly=1
  local pg_host="" pg_user="" pg_db="" mysql_host="" mysql_user="" mysql_db=""
  local alert_telegram=false tg_token="" tg_chat=""

  while [[ $# -gt 0 ]]; do
    case $1 in
      --repo) repo="$2"; shift 2 ;;
      --source) sources="$2"; shift 2 ;;
      --passphrase-file) passfile="$2"; shift 2 ;;
      --keep-daily) keep_daily="$2"; shift 2 ;;
      --keep-weekly) keep_weekly="$2"; shift 2 ;;
      --keep-monthly) keep_monthly="$2"; shift 2 ;;
      --keep-yearly) keep_yearly="$2"; shift 2 ;;
      --pg-host) pg_host="$2"; shift 2 ;;
      --pg-user) pg_user="$2"; shift 2 ;;
      --pg-db) pg_db="$2"; shift 2 ;;
      --mysql-host) mysql_host="$2"; shift 2 ;;
      --mysql-user) mysql_user="$2"; shift 2 ;;
      --mysql-db) mysql_db="$2"; shift 2 ;;
      --alert-telegram) alert_telegram=true; shift ;;
      --telegram-token) tg_token="$2"; shift 2 ;;
      --telegram-chat) tg_chat="$2"; shift 2 ;;
      *) echo "Unknown option: $1"; exit 1 ;;
    esac
  done

  [[ -z "$repo" ]] && { echo "❌ --repo is required"; exit 1; }
  [[ -z "$sources" ]] && { echo "❌ --source is required (comma-separated paths)"; exit 1; }

  # Build source list
  local source_yaml=""
  IFS=',' read -ra SRC_ARR <<< "$sources"
  for src in "${SRC_ARR[@]}"; do
    source_yaml+="  - $(echo "$src" | xargs)"$'\n'
  done

  # Build config
  cat > "$BORGMATIC_CONFIG" << YAML
# Generated by Borgmatic Backup Manager
# $(date -u +%Y-%m-%dT%H:%M:%SZ)

repositories:
  - path: $repo
    label: primary

source_directories:
${source_yaml}
exclude_patterns:
  - "*.pyc"
  - "*/.cache"
  - "*/node_modules"
  - "*/__pycache__"
  - "*/venv"
  - "*/.git"
  - "*.log"

exclude_if_present:
  - .nobackup

$([ -n "$passfile" ] && echo "encryption_passphrase_file: $passfile" || echo "# Set BORG_PASSPHRASE env var or add encryption_passphrase_file")

compression: lz4

retention:
  keep_daily: $keep_daily
  keep_weekly: $keep_weekly
  keep_monthly: $keep_monthly
  keep_yearly: $keep_yearly

checks:
  - name: repository
    frequency: 2 weeks
  - name: archives
    frequency: 1 month
YAML

  # PostgreSQL hook
  if [[ -n "$pg_host" && -n "$pg_db" ]]; then
    cat >> "$BORGMATIC_CONFIG" << YAML

postgresql_databases:
YAML
    IFS=',' read -ra PG_DBS <<< "$pg_db"
    for db in "${PG_DBS[@]}"; do
      cat >> "$BORGMATIC_CONFIG" << YAML
  - name: $(echo "$db" | xargs)
    hostname: $pg_host
    username: ${pg_user:-postgres}
YAML
    done
  fi

  # MySQL hook
  if [[ -n "$mysql_host" && -n "$mysql_db" ]]; then
    cat >> "$BORGMATIC_CONFIG" << YAML

mysql_databases:
YAML
    IFS=',' read -ra MY_DBS <<< "$mysql_db"
    for db in "${MY_DBS[@]}"; do
      cat >> "$BORGMATIC_CONFIG" << YAML
  - name: $(echo "$db" | xargs)
    hostname: $mysql_host
    username: ${mysql_user:-root}
YAML
    done
  fi

  # Telegram alert hook
  if [[ "$alert_telegram" == "true" && -n "$tg_token" && -n "$tg_chat" ]]; then
    cat > /etc/borgmatic/hooks/alert-telegram.sh << 'ALERTSCRIPT'
#!/bin/bash
ERROR_MSG="${1:-Unknown error}"
REPO="${2:-unknown}"
TOKEN="${TELEGRAM_BOT_TOKEN}"
CHAT="${TELEGRAM_CHAT_ID}"
HOST=$(hostname)
curl -s -X POST "https://api.telegram.org/bot${TOKEN}/sendMessage" \
  -d chat_id="${CHAT}" \
  -d parse_mode=HTML \
  -d text="🚨 <b>Backup FAILED</b>
Host: ${HOST}
Repo: ${REPO}
Error: ${ERROR_MSG}
Time: $(date '+%Y-%m-%d %H:%M:%S')" > /dev/null
ALERTSCRIPT
    chmod +x /etc/borgmatic/hooks/alert-telegram.sh

    cat >> "$BORGMATIC_CONFIG" << YAML

hooks:
  on_error:
    - TELEGRAM_BOT_TOKEN="$tg_token" TELEGRAM_CHAT_ID="$tg_chat" bash /etc/borgmatic/hooks/alert-telegram.sh "{error}" "{repository}"
YAML
  fi

  log "✅ Config written to $BORGMATIC_CONFIG"
  log "📋 Sources: $sources"
  log "📦 Repository: $repo"
  log "🔄 Retention: ${keep_daily}d/${keep_weekly}w/${keep_monthly}m/${keep_yearly}y"
}

# ─── BACKUP ─────────────────────────────────────────────
cmd_backup() {
  local config_flag="" dry_run=""
  while [[ $# -gt 0 ]]; do
    case $1 in
      --config) config_flag="-c $2"; shift 2 ;;
      --dry-run) dry_run="--dry-run"; shift ;;
      *) echo "Unknown option: $1"; exit 1 ;;
    esac
  done

  log "🔒 Starting encrypted backup..."

  if [[ -n "$dry_run" ]]; then
    log "📋 Dry run mode — no changes will be made"
    borgmatic create $config_flag --dry-run --verbosity 1 2>&1 | tee -a "$LOG_FILE"
  else
    borgmatic create $config_flag --verbosity 1 2>&1 | tee -a "$LOG_FILE"
    log "🧹 Pruning old archives..."
    borgmatic prune $config_flag 2>&1 | tee -a "$LOG_FILE"
    borgmatic compact $config_flag 2>&1 | tee -a "$LOG_FILE"
    log "✅ Backup and prune complete"
  fi
}

# ─── LIST ───────────────────────────────────────────────
cmd_list() {
  borgmatic list --verbosity 1
}

# ─── RESTORE ────────────────────────────────────────────
cmd_restore() {
  local archive="latest" target="" path=""
  while [[ $# -gt 0 ]]; do
    case $1 in
      --archive) archive="$2"; shift 2 ;;
      --target) target="$2"; shift 2 ;;
      --path) path="$2"; shift 2 ;;
      *) echo "Unknown option: $1"; exit 1 ;;
    esac
  done

  [[ -z "$target" ]] && { echo "❌ --target is required (restore destination)"; exit 1; }
  mkdir -p "$target"

  log "📦 Restoring archive: $archive → $target"

  if [[ -n "$path" ]]; then
    borgmatic extract --archive "$archive" --destination "$target" --path "$path"
  else
    borgmatic extract --archive "$archive" --destination "$target"
  fi

  log "✅ Restore complete: $target"
}

# ─── CHECK ──────────────────────────────────────────────
cmd_check() {
  local full=""
  while [[ $# -gt 0 ]]; do
    case $1 in
      --full) full="--only data"; shift ;;
      *) echo "Unknown option: $1"; exit 1 ;;
    esac
  done

  log "🔍 Checking repository integrity..."
  if [[ -n "$full" ]]; then
    borgmatic check $full --verbosity 1 2>&1 | tee -a "$LOG_FILE"
  else
    borgmatic check --verbosity 1 2>&1 | tee -a "$LOG_FILE"
  fi
  log "✅ Integrity check passed"
}

# ─── STATUS ─────────────────────────────────────────────
cmd_status() {
  log "📊 Backup Status"
  echo ""
  borgmatic info --verbosity 1 2>/dev/null || echo "No borgmatic config found. Run 'configure' first."
  echo ""
  echo "Last backup log entries:"
  tail -5 "$LOG_FILE" 2>/dev/null || echo "No logs yet."
}

# ─── SCHEDULE ───────────────────────────────────────────
cmd_schedule() {
  local cron_expr="0 2 * * *"
  while [[ $# -gt 0 ]]; do
    case $1 in
      --cron) cron_expr="$2"; shift 2 ;;
      *) echo "Unknown option: $1"; exit 1 ;;
    esac
  done

  local cron_line="$cron_expr root borgmatic --verbosity -1 --syslog-verbosity 1 >> $LOG_FILE 2>&1"

  echo "$cron_line" | sudo tee /etc/cron.d/borgmatic > /dev/null
  sudo chmod 644 /etc/cron.d/borgmatic
  log "✅ Scheduled: $cron_expr"
  log "📋 Cron file: /etc/cron.d/borgmatic"
}

# ─── MAIN ───────────────────────────────────────────────
COMMAND="${1:-help}"
shift || true

case "$COMMAND" in
  init)      cmd_init "$@" ;;
  configure) cmd_configure "$@" ;;
  backup)    cmd_backup "$@" ;;
  list)      cmd_list "$@" ;;
  restore)   cmd_restore "$@" ;;
  check)     cmd_check "$@" ;;
  status)    cmd_status "$@" ;;
  schedule)  cmd_schedule "$@" ;;
  help|--help|-h)
    echo "Borgmatic Backup Manager"
    echo ""
    echo "Commands:"
    echo "  init       — Initialize a new Borg repository"
    echo "  configure  — Generate borgmatic config"
    echo "  backup     — Run backup (create + prune)"
    echo "  list       — List available archives"
    echo "  restore    — Restore files from an archive"
    echo "  check      — Verify repository integrity"
    echo "  status     — Show backup status and last run info"
    echo "  schedule   — Set up cron schedule"
    echo ""
    echo "Use --help on any command for options."
    ;;
  *)
    echo "❌ Unknown command: $COMMAND"
    echo "Run with 'help' for usage."
    exit 1
    ;;
esac
