#!/bin/bash
set -euo pipefail

# Diun Setup Script — Docker Image Update Notifier
# Usage: bash setup.sh [options]

DIUN_CONFIG_DIR="${HOME}/.config/diun"
DIUN_CONFIG="${DIUN_CONFIG_DIR}/diun.yml"
PROVIDER="docker"
SCHEDULE="0 */6 * * *"
NOTIFY="telegram"
IMAGES=""
WEBHOOK_URL=""
NTFY_TOPIC="docker-updates"
LABELS=false

usage() {
  cat << 'EOF'
Usage: bash setup.sh [options]

Options:
  --provider <docker|file>       Image provider (default: docker)
  --schedule <cron>              Check schedule (default: "0 */6 * * *")
  --notify <telegram|webhook|ntfy|mail>  Notification method
  --images <img1,img2,...>       Comma-separated images (for file provider)
  --labels                       Only watch containers with diun.enable=true label
  --webhook-url <url>            Webhook URL (for webhook notify)
  --ntfy-topic <topic>           Ntfy topic (for ntfy notify)
  -h, --help                     Show this help

Environment variables:
  TELEGRAM_BOT_TOKEN    Telegram bot token
  TELEGRAM_CHAT_ID      Telegram chat ID
  SMTP_USER             SMTP username (for mail notify)
  SMTP_PASS             SMTP password
EOF
  exit 0
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --provider) PROVIDER="$2"; shift 2 ;;
    --schedule) SCHEDULE="$2"; shift 2 ;;
    --notify) NOTIFY="$2"; shift 2 ;;
    --images) IMAGES="$2"; shift 2 ;;
    --labels) LABELS=true; shift ;;
    --webhook-url) WEBHOOK_URL="$2"; shift 2 ;;
    --ntfy-topic) NTFY_TOPIC="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Install Diun if not present
install_diun() {
  if command -v diun &>/dev/null; then
    echo "✅ Diun already installed: $(diun --version 2>&1 | head -1)"
    return
  fi

  echo "📦 Installing Diun..."
  DIUN_VERSION=$(curl -s https://api.github.com/repos/crazy-max/diun/releases/latest | jq -r .tag_name)
  ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/;s/armv7l/armv7/')

  TMPDIR=$(mktemp -d)
  curl -sSL "https://github.com/crazy-max/diun/releases/download/${DIUN_VERSION}/diun_${DIUN_VERSION#v}_linux_${ARCH}.tar.gz" | tar xz -C "$TMPDIR"

  if [ -w /usr/local/bin ]; then
    mv "$TMPDIR/diun" /usr/local/bin/diun
  else
    sudo mv "$TMPDIR/diun" /usr/local/bin/diun
  fi
  chmod +x /usr/local/bin/diun
  rm -rf "$TMPDIR"

  echo "✅ Diun $(diun --version 2>&1 | head -1) installed"
}

# Generate config
generate_config() {
  mkdir -p "$DIUN_CONFIG_DIR"

  cat > "$DIUN_CONFIG" << YAML
# Diun configuration — generated by setup.sh
# Docs: https://crazymax.dev/diun/

watch:
  schedule: "${SCHEDULE}"
  firstCheckNotif: false
  compareDigest: true

defaults:
  watchRepo: false
  maxTags: 10
  excludeTags:
    - "^sha-"
    - ".*rc.*"
    - ".*alpha.*"
    - ".*beta.*"

YAML

  # Provider section
  echo "providers:" >> "$DIUN_CONFIG"
  if [ "$PROVIDER" = "docker" ]; then
    if [ "$LABELS" = true ]; then
      cat >> "$DIUN_CONFIG" << 'YAML'
  docker:
    watchByDefault: false
    watchStopped: false
YAML
    else
      cat >> "$DIUN_CONFIG" << 'YAML'
  docker:
    watchByDefault: true
    watchStopped: false
YAML
    fi
  elif [ "$PROVIDER" = "file" ]; then
    cat >> "$DIUN_CONFIG" << YAML
  file:
    filename: ${DIUN_CONFIG_DIR}/images.yml
YAML
    # Generate images file
    if [ -n "$IMAGES" ]; then
      echo "# Watched images" > "${DIUN_CONFIG_DIR}/images.yml"
      IFS=',' read -ra IMG_ARRAY <<< "$IMAGES"
      for img in "${IMG_ARRAY[@]}"; do
        img=$(echo "$img" | xargs)  # trim whitespace
        # Add docker.io prefix if no registry specified
        if [[ "$img" != *"/"*"/"* ]] && [[ "$img" != *"."*"/"* ]]; then
          img="docker.io/library/${img}"
        fi
        echo "- name: ${img}" >> "${DIUN_CONFIG_DIR}/images.yml"
      done
      echo "✅ Images file: ${DIUN_CONFIG_DIR}/images.yml"
    fi
  fi

  # Notification section
  echo "" >> "$DIUN_CONFIG"
  echo "notif:" >> "$DIUN_CONFIG"
  case "$NOTIFY" in
    telegram)
      if [ -z "${TELEGRAM_BOT_TOKEN:-}" ] || [ -z "${TELEGRAM_CHAT_ID:-}" ]; then
        echo "⚠️  Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID environment variables"
      fi
      cat >> "$DIUN_CONFIG" << 'YAML'
  telegram:
    token: "${TELEGRAM_BOT_TOKEN}"
    chatIDs:
      - ${TELEGRAM_CHAT_ID}
    templateBody: |
      🐳 *Docker Image Update*
      Image: `{{ .Entry.Image }}`
      Status: {{ .Entry.Status }}
      {{ if .Entry.Manifest.Platform }}Platform: {{ .Entry.Manifest.Platform }}{{ end }}
YAML
      ;;
    webhook)
      cat >> "$DIUN_CONFIG" << YAML
  webhook:
    endpoint: "${WEBHOOK_URL}"
    method: POST
    headers:
      Content-Type: application/json
YAML
      ;;
    ntfy)
      cat >> "$DIUN_CONFIG" << YAML
  ntfy:
    endpoint: "https://ntfy.sh"
    topic: "${NTFY_TOPIC}"
    priority: 3
    timeout: 10s
YAML
      ;;
    mail)
      cat >> "$DIUN_CONFIG" << 'YAML'
  mail:
    host: "smtp.gmail.com"
    port: 587
    ssl: false
    startTLS: true
    username: "${SMTP_USER}"
    password: "${SMTP_PASS}"
    from: "${SMTP_USER}"
    to: "${SMTP_USER}"
YAML
      ;;
  esac

  echo "✅ Config written to: ${DIUN_CONFIG}"
}

# Main
echo "🐳 Diun Setup — Docker Image Update Notifier"
echo "=============================================="
install_diun
generate_config

echo ""
echo "🎉 Setup complete!"
echo ""
echo "Test notifications:"
echo "  diun serve --config ${DIUN_CONFIG} --test-notif"
echo ""
echo "Run a check now:"
echo "  diun serve --config ${DIUN_CONFIG}"
echo ""
echo "Install as systemd service:"
echo "  bash scripts/install-service.sh"
