#!/bin/bash
# Node-RED Manager — Reverse Proxy Config Generator
set -euo pipefail

DOMAIN=""
PORT="${NODE_RED_PORT:-1880}"

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain) DOMAIN="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    *) echo "Usage: bash scripts/proxy.sh --domain nodered.example.com [--port 1880]"; exit 1 ;;
  esac
done

if [ -z "$DOMAIN" ]; then
  echo "Usage: bash scripts/proxy.sh --domain nodered.example.com [--port 1880]"
  exit 1
fi

echo "🌐 Generating reverse proxy config for $DOMAIN → localhost:$PORT"

# Detect available proxy
if command -v nginx &>/dev/null; then
  CONF_PATH="/etc/nginx/sites-available/nodered"

  cat > /tmp/nodered-nginx.conf <<EOF
# Node-RED reverse proxy — generated by Node-RED Manager
server {
    listen 80;
    server_name $DOMAIN;

    location / {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

  echo "📄 Nginx config generated: /tmp/nodered-nginx.conf"
  echo ""

  if [ -w /etc/nginx/sites-available/ ] || [ "$(id -u)" -eq 0 ]; then
    cp /tmp/nodered-nginx.conf "$CONF_PATH"
    ln -sf "$CONF_PATH" /etc/nginx/sites-enabled/nodered
    nginx -t && systemctl reload nginx
    echo "✅ Nginx configured and reloaded"
  else
    echo "Copy to Nginx (requires sudo):"
    echo "  sudo cp /tmp/nodered-nginx.conf $CONF_PATH"
    echo "  sudo ln -sf $CONF_PATH /etc/nginx/sites-enabled/nodered"
    echo "  sudo nginx -t && sudo systemctl reload nginx"
  fi

  echo ""
  echo "Get SSL certificate:"
  echo "  sudo certbot --nginx -d $DOMAIN"

elif command -v caddy &>/dev/null; then
  cat > /tmp/nodered-Caddyfile <<EOF
$DOMAIN {
    reverse_proxy localhost:$PORT
}
EOF

  echo "📄 Caddyfile generated: /tmp/nodered-Caddyfile"
  echo ""
  echo "Add to your Caddyfile:"
  echo "  cat /tmp/nodered-Caddyfile >> /etc/caddy/Caddyfile"
  echo "  sudo systemctl reload caddy"
  echo ""
  echo "Caddy handles SSL automatically! 🔒"

else
  echo "⚠️  No reverse proxy detected (nginx/caddy)."
  echo ""
  echo "Install one:"
  echo "  sudo apt install nginx   # then re-run this script"
  echo "  # OR"
  echo "  sudo apt install caddy"
fi
