#!/bin/bash
# Create a persistent Logwatch configuration override
set -e

DETAIL="Med"
RANGE="yesterday"
FORMAT="text"
OUTPUT="stdout"
FILENAME=""
MAILTO=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --detail)   DETAIL="$2"; shift 2 ;;
    --range)    RANGE="$2"; shift 2 ;;
    --format)   FORMAT="$2"; shift 2 ;;
    --output)   OUTPUT="$2"; shift 2 ;;
    --filename) FILENAME="$2"; shift 2 ;;
    --mailto)   MAILTO="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: configure.sh [OPTIONS]"
      echo "Creates /etc/logwatch/conf/logwatch.conf override"
      echo ""
      echo "Options:"
      echo "  --detail LOW|MED|HIGH  Default detail level"
      echo "  --range RANGE          Default date range"
      echo "  --format text|html     Default output format"
      echo "  --output stdout|mail|file  Default output type"
      echo "  --filename PATH        Default output file path"
      echo "  --mailto ADDRESS       Default email recipient"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

CONF_FILE="/etc/logwatch/conf/logwatch.conf"
sudo mkdir -p /etc/logwatch/conf

cat <<EOF | sudo tee "$CONF_FILE" > /dev/null
# Logwatch Configuration — Generated by logwatch-reports skill
# $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# This overrides defaults in /usr/share/logwatch/default.conf/logwatch.conf
# Edit this file to change default behavior.

# Output type: stdout, mail, or file
Output = $OUTPUT

# Default detail level: Low, Med, High, or 0-10
Detail = $DETAIL

# Default date range
Range = $RANGE

# Output format: text or html
Format = $FORMAT
EOF

if [[ -n "$MAILTO" ]]; then
  echo "MailTo = $MAILTO" | sudo tee -a "$CONF_FILE" > /dev/null
fi

if [[ -n "$FILENAME" ]]; then
  echo "Filename = $FILENAME" | sudo tee -a "$CONF_FILE" > /dev/null
fi

echo "✅ Configuration saved to $CONF_FILE"
echo ""
cat "$CONF_FILE"
