#!/bin/bash
# Minecraft Server Installer
# Downloads and configures a Minecraft Java Edition server

set -euo pipefail

MC_DIR="${MC_DIR:-$HOME/minecraft-server}"
MC_VERSION=""
MC_TYPE="vanilla"
INSTALL_SYSTEMD=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --version) MC_VERSION="$2"; shift 2 ;;
    --type) MC_TYPE="$2"; shift 2 ;;
    --systemd) INSTALL_SYSTEMD=true; shift ;;
    --dir) MC_DIR="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: install.sh [OPTIONS]"
      echo "  --version VERSION   Minecraft version (default: latest)"
      echo "  --type TYPE         Server type: vanilla, paper, fabric, forge (default: vanilla)"
      echo "  --systemd           Install systemd service"
      echo "  --dir DIR           Server directory (default: ~/minecraft-server)"
      exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Check dependencies
for cmd in java curl jq screen; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "❌ Missing dependency: $cmd"
    echo "   Install: sudo apt-get install -y openjdk-21-jre-headless screen curl jq"
    exit 1
  fi
done

# Check Java version
JAVA_VER=$(java -version 2>&1 | head -1 | cut -d'"' -f2 | cut -d'.' -f1)
if [[ "$JAVA_VER" -lt 17 ]]; then
  echo "❌ Java 17+ required (found Java $JAVA_VER)"
  echo "   Install: sudo apt-get install -y openjdk-21-jre-headless"
  exit 1
fi
echo "✅ Java $JAVA_VER detected"

# Create server directory
mkdir -p "$MC_DIR"
cd "$MC_DIR"

# Get latest version if not specified
if [[ -z "$MC_VERSION" ]]; then
  echo "🔍 Fetching latest Minecraft version..."
  MC_VERSION=$(curl -s https://launchermeta.mojang.com/mc/game/version_manifest_v2.json | jq -r '.latest.release')
  echo "📦 Latest version: $MC_VERSION"
fi

# Download server JAR based on type
case "$MC_TYPE" in
  vanilla)
    echo "⬇️  Downloading Vanilla server $MC_VERSION..."
    MANIFEST_URL=$(curl -s https://launchermeta.mojang.com/mc/game/version_manifest_v2.json | \
      jq -r --arg v "$MC_VERSION" '.versions[] | select(.id==$v) | .url')
    
    if [[ -z "$MANIFEST_URL" || "$MANIFEST_URL" == "null" ]]; then
      echo "❌ Version $MC_VERSION not found"
      exit 1
    fi
    
    SERVER_URL=$(curl -s "$MANIFEST_URL" | jq -r '.downloads.server.url')
    SERVER_SHA1=$(curl -s "$MANIFEST_URL" | jq -r '.downloads.server.sha1')
    
    curl -sL "$SERVER_URL" -o server.jar
    
    # Verify checksum
    ACTUAL_SHA1=$(sha1sum server.jar | cut -d' ' -f1)
    if [[ "$ACTUAL_SHA1" != "$SERVER_SHA1" ]]; then
      echo "❌ Checksum mismatch! Download may be corrupted."
      rm server.jar
      exit 1
    fi
    echo "✅ Downloaded server.jar (verified SHA1)"
    ;;
    
  paper)
    echo "⬇️  Downloading Paper server for $MC_VERSION..."
    # Get latest Paper build for this MC version
    PAPER_BUILDS=$(curl -s "https://api.papermc.io/v2/projects/paper/versions/$MC_VERSION/builds" 2>/dev/null)
    if [[ $? -ne 0 ]] || echo "$PAPER_BUILDS" | jq -e '.error' &>/dev/null; then
      echo "❌ Paper not available for version $MC_VERSION"
      exit 1
    fi
    
    LATEST_BUILD=$(echo "$PAPER_BUILDS" | jq -r '.builds[-1].build')
    JAR_NAME=$(echo "$PAPER_BUILDS" | jq -r '.builds[-1].downloads.application.name')
    
    curl -sL "https://api.papermc.io/v2/projects/paper/versions/$MC_VERSION/builds/$LATEST_BUILD/downloads/$JAR_NAME" -o server.jar
    echo "✅ Downloaded Paper build #$LATEST_BUILD"
    ;;
    
  fabric)
    echo "⬇️  Downloading Fabric server for $MC_VERSION..."
    FABRIC_LOADER=$(curl -s "https://meta.fabricmc.net/v2/versions/loader" | jq -r '.[0].version')
    FABRIC_INSTALLER=$(curl -s "https://meta.fabricmc.net/v2/versions/installer" | jq -r '.[0].version')
    
    curl -sL "https://meta.fabricmc.net/v2/versions/loader/$MC_VERSION/$FABRIC_LOADER/$FABRIC_INSTALLER/server/jar" -o server.jar
    echo "✅ Downloaded Fabric server (loader $FABRIC_LOADER)"
    ;;
    
  forge)
    echo "⚠️  Forge requires manual download from https://files.minecraftforge.net/"
    echo "   Download the installer JAR and run: java -jar forge-installer.jar --installServer"
    exit 1
    ;;
    
  *)
    echo "❌ Unknown server type: $MC_TYPE (use: vanilla, paper, fabric, forge)"
    exit 1 ;;
esac

# Accept EULA
echo "eula=true" > eula.txt
echo "✅ EULA accepted"

# Generate default server.properties if not exists
if [[ ! -f server.properties ]]; then
  cat > server.properties <<'PROPS'
# Minecraft Server Properties
# Generated by minecraft-server skill

# Performance
max-players=20
view-distance=10
simulation-distance=8
max-tick-time=60000
network-compression-threshold=256

# Gameplay
difficulty=normal
gamemode=survival
pvp=true
spawn-protection=16
allow-nether=true
allow-flight=false
spawn-monsters=true
spawn-animals=true

# Network
server-port=25565
online-mode=true
motd=\u00a7bMinecraft Server \u00a77- Powered by OpenClaw

# Security
white-list=true
enforce-whitelist=true
max-world-size=29999984

# World
level-name=world
level-type=minecraft\:normal
generate-structures=true
PROPS
  echo "✅ server.properties configured"
fi

# Create directories
mkdir -p backups logs

# Save version info
cat > .mc-info.json <<EOF
{
  "version": "$MC_VERSION",
  "type": "$MC_TYPE",
  "installed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "java_version": "$JAVA_VER",
  "directory": "$MC_DIR"
}
EOF

# Install systemd service
if $INSTALL_SYSTEMD; then
  CURRENT_USER=$(whoami)
  sudo tee /etc/systemd/system/minecraft.service > /dev/null <<EOF
[Unit]
Description=Minecraft Server
After=network.target

[Service]
User=$CURRENT_USER
WorkingDirectory=$MC_DIR
ExecStart=/usr/bin/java -Xms${MC_MIN_RAM:-2G} -Xmx${MC_MAX_RAM:-4G} -jar server.jar nogui
ExecStop=/usr/bin/screen -S minecraft -X stuff "stop\n"
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl daemon-reload
  sudo systemctl enable minecraft
  echo "✅ Systemd service installed (minecraft.service)"
fi

echo ""
echo "🎮 Minecraft Server $MC_VERSION ($MC_TYPE) installed at $MC_DIR"
echo "   Start: bash scripts/start.sh"
echo "   Port: 25565 (edit server.properties to change)"
